### ISSUE TITLE
Misleadling verbalization of speed up / slow down

### ISSUE THREAD

**Issue by andreasabel** [Bodigrim/tasty-bench#31]
I was surprised that a
1. "75% faster than baseline" (see https://gitlab.haskell.org/ghc/ghc/-/merge_requests/8072#note_427599)
2. was advertised as "4 times faster" (see https://github.com/haskell/core-libraries-committee/issues/59#issue-1227722396)

75% faster means 1.75 times as fast, so, which one is true?  Turns out "4 times faster" is (sort of) true, but the verbalization of the speed up is incorrect:
https://github.com/Bodigrim/tasty-bench/blob/fc8f806cbd4596aba61cfc58e356b2075eaa64f0/src/Test/Tasty/Bench.hs#L1763-L1770
(In this code `n` is the fraction _new duration divided by old duration_.)

The verb "faster" is about comparison of velocities.  So if run 5 km/h and you 10 km/h, you run
_5 km/h faster_ than me.  Relativising this to the baseline of my speed, you run _100% faster_ than me.  Much easier to understand is the sentence _you run 2 times as fast as me_ (where proper English would be "twice as fast").

This bug is another proof that people are just terrible when it comes to percentage calculations.

I suggest to avoid percentage calculation and also comparative adjectives (which require you to subtract the baseline).  Rather, __just print the factor__.  So,  instead of 
> 75% faster than baseline

print:
> 4.0 times as fast as the baseline

**Comment by Bodigrim** [comment]
"faster" has multitude of meanings, including ["ahead of the correct or expected time"](https://www.thefreedictionary.com/faster), ["done in comparatively short time"](https://www.dictionary.com/browse/faster), ["taking a comparatively short time"](https://www.merriam-webster.com/dictionary/fast), which is the meaning used in `tasty-bench`. This is not incorrect per se.

I agree that "75% faster" is an ambiguous statement for the reasons you described, but I'd argue that "42 ms, 75% faster than baseline" is not, because we clearly state the basis and define that we talk about time in seconds, not rate in hertz. 

Leaving aside linguistics, I cannot take a switch from "75% faster" to "faster by factor 4", because `tasty-bench` API uses percentages for [`FailIfSlower`](https://hackage.haskell.org/package/tasty-bench-0.3.1/docs/Test-Tasty-Bench.html#t:FailIfSlower) and [`FailIfFaster`](https://hackage.haskell.org/package/tasty-bench-0.3.1/docs/Test-Tasty-Bench.html#t:FailIfFaster). It would be very much confusing do not use the same units for reporting. 

What if we change "42 ms, 75% faster than baseline" to "42 ms, 75% less than baseline"? Would it be less ambiguous?

**Comment by andreasabel** [comment]
> "42 ms, 75% less than baseline"?

Yes, this is unambiguous.  +1

**Comment by Bodigrim** [comment]
Closed by fce531307fd58f2b94f81ce4c8445c693fae070b

**Comment by andreasabel** [comment]
Thanks for fixing!
