### ISSUE TITLE
CSV output appears to be incompatible with criterion-compare

### ISSUE THREAD

**Issue by sjakobi** [Bodigrim/tasty-bench#4]
[`criterion-compare`](http://hackage.haskell.org/package/criterion-compare) is a nice tool for visualizing diffs between benchmark runs. AFAIK it can digest the CSV output from both `criterion` and `gauge`. It seems unable to handle the output from `tasty-bench` though. Given

```
Name,Mean (ps),2*Stdev (ps)
All.Data.ByteString.Builder.Encoding wrappers.primMapListFixed word8 (10000),27122086,1442142
All.Data.ByteString.Builder.Encoding wrappers.primUnfoldrFixed word8 (10000),7367723,667980
All.Data.ByteString.Builder.Encoding wrappers.primMapByteStringFixed word8 (10000),4706674,282574
All.Data.ByteString.Builder.Encoding wrappers.primMapLazyByteStringFixed word8 (10000),4794733,344816
```

it says:

```
$ criterion-compare bench.csv bench.csv 
criterion-compare: user error (parse error (Failed reading: conversion error: empty) at 
All.Data.ByteString.Builder.Encoding wrappers.primUnfoldrFixed word8 (10000),7367723,667980
All.Dat (truncated))
```

Or should I possibly use a different tool for viewing the diffs?

**Comment by sjakobi** [comment]
I'll give https://github.com/Bodigrim/tasty-bench#comparison-against-baseline a try…

**Comment by Bodigrim** [comment]
`criterion-compare` expects CSV contain exactly 7 columns (https://github.com/AndreasPK/criterion-compare/blob/13ec87146ab48f706a75476b8e952ae979afd0b8/src/CsvParse.hs#L19-L30), while `tasty-bench` generates only three, corresponding to the first (`getBenchName`), second (`statsMean`) and fifth (doubled `statsStd`) columns in `criterion` output. 

I cannot fix this on `tasty-bench` side simply because I do not have missing data (which is confidence intervals for mean and stdev). Could probably worked around on `criterion-compare` side, but after all it is for `criterion`.

The simplest workaround is `awk 'BEGIN {FS=","; OFS=","} ; {print $1,$2,$2,$2,$3/2,$3/2,$3/2}'`.

**Comment by Bodigrim** [comment]
Actually, I can add a command-line switch to fake `criterion` compatible output.

**Comment by Bodigrim** [comment]
After more consideration, I'm reluctant to fix this. In general it's wrong to compare reports produced by different benchmark frameworks, especially by faking non-existing data. 

To be honest, I do not feel much need in a dedicated package of this sort, because any tool from Excel to gnuplot is sufficient to plot data from two CSVs. I cannot even build `criterion-compare` with GHC 8.10: several of its dependencies restrict `base < 4.14` or worse. And when I throw `allow-newer`, build fails with `can't load framework: Cocoa (not found)`.
